# Site settings
title: Jens Raaby
email: firstname@lastname.co.uk
timezone: Europe/London

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jens.raaby.co.uk" # the base hostname & protocol for your site
twitter_username: jraaby
github_username:  jensraaby
permalink: /juornal/:year/:month/:day/:title/

# Build settings
markdown: kramdown
